// apps/hr-module/src/layouts/Sidebar.vue


<template>
  <div
    class="hidden md:block bg-muted/40 fixed top-0 left-0 h-full w-[220px] lg:w-[260px]"
  >
    <div class="flex h-full flex-col">
      <!-- Header -->
      <div class="flex h-14 items-center px-4 lg:h-[60px] lg:px-6 bg-blue-400 border-r border-b">
        <router-link to="/" class="flex items-center gap-2 font-semibold">
          <RiHotelLine class="w-8 h-8" />
          <span>ERP Entry</span>
        </router-link>
      </div>

      <!-- Navigation Links -->
      <div class="flex-1 bg-blue-50 pt-4 flex flex-col">
        <nav class="grid items-start px-2 text-sm font-medium lg:px-4">
          <router-link
            v-for="link in links"
            :key="link.text"
            :to="link.to"
            class="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
          >
            <component :is="link.icon" class="h-5 w-5" />
            {{ link.text }}
          </router-link>
        </nav>

        <!-- Logout Button -->
        <div class="ml-10 mt-auto mb-6">
          <router-link
            to="/logout"
            class="flex items-center justify-center gap-3 text-center rounded-lg bg-red-600 text-white py-2 px-4 hover:bg-red-500 transition w-[60%]"
          >
            <LogOut class="h-5 w-5" />
            Logout
          </router-link>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { LogOut, Home, ShoppingCart, LineChart, Users } from 'lucide-vue-next';
//  import { RiHotelLine } from 'lucide-vue-next'; // assuming ShadCN has RiHotelLine

const links = [
  { text: 'Dashboard', to: '/', icon: Home },
  { text: 'Orders', to: '/orders', icon: ShoppingCart },
  { text: 'Analytics', to: '/analytics', icon: LineChart },
  { text: 'Customers', to: '/customers', icon: Users },
];
</script>

// apps/booking-app/src/components/Navbar/sidebar.tsx
import { Link } from 'react-router-dom'
import {
  Home,
  LineChart,
  Package,
  Package2,
  ShoppingCart,
  Users,
} from 'lucide-react'

export const description =
  'A products dashboard with a sidebar navigation and a main content area. The dashboard has a header with a search input and a user menu. The sidebar has a logo, navigation links, and a card with a call to action. The main content area shows an empty state with a call to action.'

const Sidebar = () => {
  return (
    <div className="hidden border-r bg-muted/40 md:block fixed top-0 left-0 h-full w-[220px] lg:w-[280px] ">
      <div className="flex h-full max-h-screen flex-col gap-2">
        <div className="flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6 bg-green-400">
          <Link to="/" className="flex items-center gap-2 font-semibold">
            <Package2 className="h-6 w-6" />
            <span className="">Booking App</span>
          </Link>
          {/* <Button variant="outline" size="icon" className="ml-auto h-8 w-8">
            <Bell className="h-4 w-4" />
            <span className="sr-only">Toggle notifications</span>
          </Button> */}
        </div>
        <div className="flex-1">
          <nav className="grid items-start px-2 text-sm font-medium lg:px-4">
            <Link
              to="/"
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
            >
              <Home className="h-4 w-4" />
              Dashboard
            </Link>
            <Link
              to="/booking/add"
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
            >
              <ShoppingCart className="h-4 w-4" />
              Add Booking
            </Link>
            <Link
              to="bookings"
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
            >
              <Package className="h-4 w-4" />
              View Booking
            </Link>
            <Link
              to="registration/add"
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
            >
              <Users className="h-4 w-4" />
              Guest Registration
            </Link>
            <Link
              to="registrations"
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
            >
              <LineChart className="h-4 w-4" />
              View Registration
            </Link>
            <Link
              to="reports"
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
            >
              <LineChart className="h-4 w-4" />
              Reports
            </Link>
          </nav>
        </div>
      </div>
    </div>
  )
}

export default Sidebar
